# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Acer/Desktop/parte_previa_lab_6/parte_previa_lab_6.cache/wt [current_project]
set_property parent.project_path C:/Users/Acer/Desktop/parte_previa_lab_6/parte_previa_lab_6.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/Acer/Desktop/parte_previa_lab_6/parte_previa_lab_6.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/Acer/Desktop/ELO212-example-modules-master/Lab6_PS2_VGA_reference/characters.v
  C:/Users/Acer/Desktop/parte_previa_lab_6/parte_previa_lab_6.srcs/sources_1/new/clk_wiz_0_clk_wiz.v
  C:/Users/Acer/Desktop/parte_previa_lab_6/parte_previa_lab_6.srcs/sources_1/new/kbd_ms.v
  C:/Users/Acer/Desktop/parte_previa_lab_6/parte_previa_lab_6.srcs/sources_1/new/cursor.v
  C:/Users/Acer/Desktop/parte_previa_lab_6/parte_previa_lab_6.srcs/sources_1/new/hello_world.v
  C:/Users/Acer/Desktop/parte_previa_lab_6/parte_previa_lab_6.srcs/sources_1/new/template.v
  C:/Users/Acer/Desktop/parte_previa_lab_6/parte_previa_lab_6.srcs/sources_1/new/template_resultado.v
  C:/Users/Acer/Desktop/parte_previa_lab_6/parte_previa_lab_6.srcs/sources_1/new/m_driver_1024x768.v
  C:/Users/Acer/Desktop/parte_previa_lab_6/parte_previa_lab_6.srcs/sources_1/new/clock_wiz0.v
  C:/Users/Acer/Desktop/parte_previa_lab_6/parte_previa_lab_6.srcs/sources_1/new/lab_6_pp.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Acer/Desktop/parte_previa_lab_6/parte_previa_lab_6.srcs/constrs_1/new/constraints.xdc
set_property used_in_implementation false [get_files C:/Users/Acer/Desktop/parte_previa_lab_6/parte_previa_lab_6.srcs/constrs_1/new/constraints.xdc]


synth_design -top lab_6 -part xc7a100tcsg324-1


write_checkpoint -force -noxdef lab_6.dcp

catch { report_utilization -file lab_6_utilization_synth.rpt -pb lab_6_utilization_synth.pb }
